periodics:
  - name: kctx-release
    cron: "0 20 * * *"
    decorate: true
    extra_refs:
    - org: belitre
      repo: kctx-manager
      base_ref: master
    spec: 
      containers:
        - name: "release"
          imagePullPolicy: IfNotPresent
          command:
            - make
          args:
            - semantic-release
          image: belitre/gobuilder:latest
          env:
            - name: GH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-token
                  key: oauth
presubmits:
  belitre/kctx-manager:
    - name: build
      context: build
      decorate: true 
      always_run: true 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)build( please)?" 
      rerun_command: "build"
      spec: 
        containers:
          - name: "build"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - test
              - build-cross
            image: belitre/gobuilder:latest
   
postsubmits:
  belitre/kctx-manager:
    - name: build
      decorate: true
      max_concurrency: 1 
      branches:
        - master
      spec:
        containers:
          - name: "build"
            imagePullPolicy: IfNotPresent
            command:
              - make
            args:
              - test
              - build-cross
            image: belitre/gobuilder:latest

