#periodics:
#- interval: 10m
#  name: echo-test
#  decorate: true
#  spec:
#    containers:
#    - image: alpine
#      command: ["/bin/date"]
      
presubmits:
  belitradas/test-infra:
  - name: tests           # As for periodics.
    context: tests
    decorate: true           # As for periodics.
    always_run: true         # Run for every PR, or only when requested.
    skip_report: false        # Whether to skip setting a status on GitHub.
    max_concurrency: 2       # As for postsubmits.
    trigger: "(?m)tests( please)?" # Regexp, see discussion.
    rerun_command: "tests"  
    spec: 
      containers:
      - image: alpine
        command: ["/bin/date"]

postsubmits:
  belitradas/test-infra:
  - name: tests-postsubmit
    decorate: true
    branches:             # Regexps, only run against these branches.
    - ^master$
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]