kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: system-ingress
  namespace: default
spec:
  podSelector: {}
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              system: 'true'
  policyTypes:
    - Ingress