prowjob_namespace: default
pod_namespace: test-pods

plank:
  allow_cancellations: true
  job_url_prefix: 'https://prow.coolcluster.belitre.com/view/gcs'
  job_url_template: 'https://prow.coolcluster.belitre.com/view/gcs/belitradas-prow-artifacts/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  report_template: '[Full PR test history](https://prow.coolcluster.belitre.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})'
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 7200000000000 # 2h
    grace_period: 15000000000 # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190517-95ef25d87"
      initupload: "gcr.io/k8s-prow/initupload:v20190517-95ef25d87"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190517-95ef25d87"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190517-95ef25d87"
    gcs_configuration:
      bucket: "belitradas-prow-artifacts"
      path_strategy: "explicit"
    gcs_credentials_secret: gcs-credentials

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m

tide:
  sync_period: 2m
  merge_method:
    belitradas: squash
    belitradas/infra-test: squash
  pr_status_base_url: https://prow.coolcluster.belitre.com/pr
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: false
#    orgs:
#     belitradas:
#      required-contexts:
#        - tide
#      repos:
#        test-infra:
#          skip-unknown-contexts: true
#          from-branch-protection: true
  queries:
  - orgs:
    - belitradas
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase

branch-protection:
  allow_disabled_policies: true
  protect: false
  orgs:
    belitradas:
      protect: false
      repos:
        test-infra:
          protect: false
          branches:
            master:
              protect: true
              restrictions:
                teams: 
                  - JenkinsAccess
              enforce_admins: true  # rules apply to admins
    #          required_pull_request_reviews:
    #            dismiss_stale_reviews: true
    #            required_approving_review_count: 1
              required_status_checks:
                strict: true
                contexts: 
                  - tide