prowjob_namespace: default
pod_namespace: test-pods

plank:
  allow_cancellations: true
  job_url_prefix: 'https://prow.coolcluster.belitre.com/view/gcs'
  job_url_template: 'https://prow.coolcluster.belitre.com/view/gcs/belitradas-prow-artifacts/pr-logs/pull/{{.Spec.Refs.Repo}}/{{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}/{{.Spec.Job}}/{{.Status.BuildID}}'
  report_template: '[Full PR test history](https://prow.coolcluster.belitre.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}})'
  pod_pending_timeout: 60m
  default_decoration_config:
    timeout: 2h # 2h
    grace_period: 15s # 15s
    utility_images:
      clonerefs: "gcr.io/k8s-prow/clonerefs:v20190517-95ef25d87"
      initupload: "gcr.io/k8s-prow/initupload:v20190517-95ef25d87"
      entrypoint: "gcr.io/k8s-prow/entrypoint:v20190517-95ef25d87"
      sidecar: "gcr.io/k8s-prow/sidecar:v20190517-95ef25d87"
    gcs_configuration:
      bucket: "belitradas-prow-artifacts"
      path_strategy: "explicit"
    gcs_credentials_secret: gcs-credentials

sinker:
  resync_period: 1m
  max_prowjob_age: 48h
  max_pod_age: 30m

push_gateway:
  endpoint: pushgateway

tide:
  sync_period: 1m
  merge_method:
    belitradas: squash
    belitradas/test-infra: squash
    belitre/kctx-manager: squash
  pr_status_base_url: https://prow.coolcluster.belitre.com/pr
  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge
  context_options:
    # Use branch protection options to define required and optional contexts
    from-branch-protection: true
    # Treat unknown contexts as optional
    skip-unknown-contexts: false
  queries:
  - orgs:
    - belitradas
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase
    - do-not-merge/invalid-owners-file
  - repos:
    - belitre/kctx-manager
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    - needs-rebase
    - do-not-merge/invalid-owners-file

github_reporter:
  job_types_to_report:
  - presubmit
  - postsubmit
      
presubmits:
  belitradas/test-infra:
    - name: test-fast-config
      context: test-fast-config
      decorate: true 
      always_run: false 
      skip_report: true 
      max_concurrency: 1 
      trigger: "(?m)test-fast-config( please)?" 
      rerun_command: "test-fast-config"
      run_if_changed: '^(config/.*|prow/.*)$'
      spec: 
        containers:
          - name: "test-config"
            command:
              - checkconfig
            args:
              - --plugin-config=prow/config.yaml
              - --config-path=prow/plugins.yaml
              - --job-config-path=config/jobs
            image: belitre/checkconfig:latest
            imagePullPolicy: Always
    - name: test-prow-config
      context: test-prow-config
      decorate: true 
      always_run: false 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)test-prow-config( please)?" 
      rerun_command: "test-prow-config"
      run_if_changed: '^(config/.*|prow/.*)$'
      extra_refs:
        - base_ref: master
          org: kubernetes
          repo: test-infra
      spec: 
        containers:
          - name: "test-config"
            command:
              - ./prow/scripts/validate-config.sh
            image: launcher.gcr.io/google/bazel:0.24.1
            env:
              - name: K8S_TEST_INFRA_PATH
                value: "/home/prow/go/src/github.com/kubernetes/test-infra"
              - name: BELITRADAS_TEST_INFRA_PATH
                value: "/home/prow/go/src/github.com/belitradas/test-infra"
    - name: test-prow-manifests
      context: test-prow-manifests
      decorate: true 
      always_run: false 
      skip_report: false 
      max_concurrency: 1 
      trigger: "(?m)test-prow-manifests( please)?" 
      rerun_command: "test-prow-manifests"
      run_if_changed: 'prow/manifests/'
      spec: 
        serviceAccountName: prow
        containers:
          - name: "test-manifests"
            command:
              - make
            args:
              - deploy-prow-dry-run
            image: belitre/kubectl:1.14.2